[package]
name = "rust-wasm-builder"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>", "RickChen <xtforgame@gmail.com>"]

[lib]
path = "utils/blank.rs"

[dependencies]
wasm-bindgen = "0.2"
